name: Java CI

on:
  push:
  schedule: [ cron: '18 1 * * 5' ] # weekly: At 01:18 on Friday

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 11, 17 ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
        cache: 'maven'

    - run: mvn --batch-mode --show-version --no-transfer-progress -DCI=GitHub install
